
const ScreenIds = {

   // login-signup
   LOGIN_SCREEN_ID: 1,
   SIGNUP_SCREEN_ID: 2,
   FORGOT_PASSWORD_SCREEN_ID: 3,

   // main menu's & acc details
   MAIN_MENU_SCREEN_ID: 4,
   USER_ACC_DETAILS_SCREEN_ID: 5,

   // presentation screens
   MY_PRESENTATIONS_SCREEN_ID: 6,
   PRESENTATION_DETAILS_SCREEN_ID: 7,
   TRANSCRIPT_DETAILS_SCREEN_ID: 8,
   UPLOAD_PRESENTATION_SCREEN_ID: 9,
   PROCESSING_PRESENTATION_SCREEN_ID: 10,
   LIVE_FEEDBACK_SCREEN_ID: 11,
   NEW_PRESENTATION_ID: 22,
   CHECK_CAMERA: 23,
   LOADING_SCREEN: 24,


   // tutorials
   TUTORIAL_PRESENTATION_SCREEN_ID: 12,
   TUTORIAL_APP_SCREEN_ID: 13,
   CHAT_BOT_SCREEN_ID: 14,

   PROGRESS_TRACKING_SCREEN_ID: 15,


}


export default ScreenIds